TITLE HELLOWORLD
DEDOMENA SEGMENT
MSG DB "Hello World",10,13,"$"
DEDOMENA ENDS
KODIKAS SEGMENT
ARXH: MOV AX,DEDOMENA
MOV DS,AX
LEA DX,MSG
MOV AH,9 
INT 21H
MOV AH,4CH
INT 21H
KODIKAS ENDS
END ARXH